cpy = [
'If failure really was the best teacher, users would all be geniuses by now.',
'The pursuit of IT uptime can negatively affect enjoying personal downtime.',
'Remember … Don’t copy that floppy!',
'The early patch blocks the worm.',
'Microsoft Word crashing is the new “dog ate my homework.”',
'Said the movie cowboy to the stubborn macOS process: “I can’t force-quit you.”,
'Spiciness is they key to happiness.',
'Counting on the NSA to save your data is not a solid backup strategy.',
'Be glad you didn’t get a FORTRAN cookie. It would have been way past it’s expiration date.',
'Pro tip for users: There is no “any key.”',
'To err is human, to err all too often is user.',
'An IT pro’s work is never done.',
'You look like you could use a beer right now.',
'When making New Year’s resolutions, avoid 800 x 600.',
'A closed end user’s mouth gathers no feet.',
'You will soon hear from a long lost %USERNAME%',
'Passwords are like underwear. Change them regularly.',
'May your systems never hang, nor go out with a bang.',
'Time is an illusion. Lunchtime doubly so (especially for IT pros) — via Instinct via The Hitchhiker’s Guide to the Galaxy.',
'“…That wasn’t chicken.”',
'“A starship ride has been promised to you by the galactic wizard.”',
'“Ignore previous cookie.”',
'“Help! I am being held prisoner in a Chinese bakery!”',
'“Your tongue is your ambassador.”',
'It is most enjoyable to talk with you.',
'To truly find yourself you should play hide and seek alone.',
'Confucius say: " Turn it off and back on."',
'If failure really was the best teacher, users would all be geniuses by now.',
'The pursuit of IT uptime can negatively affect enjoying personal downtime.',
'Remember … Don’t copy that floppy!',
'The early patch blocks the worm.',
'Microsoft Word crashing is the new “dog ate my homework.”',
'Said the movie cowboy to the stubborn macOS process: “I can’t force-quit you.”',
'Spiciness is they key to happiness.',
'Counting on the NSA to save your data is not a solid backup strategy.',
'Be glad you didn’t get a FORTRAN cookie. It would have been way past it’s expiration date.',
'Pro tip for users: There is no “any key.”',
'To err is human, to err all too often is user.',
'An IT pro’s work is never done.',
'You look like you could use a beer right now.',
'When making New Year’s resolutions, avoid 800 x 600.',
'A closed end user’s mouth gathers no feet.',
'You will soon hear from a long lost %USERNAME%.',
'Passwords are like underwear. Change them regularly.',
'May your systems never hang, nor go out with a bang.',
'Time is an illusion. Lunchtime doubly so (especially for IT pros) — via Instinct via The Hitchhiker’s Guide to the Galaxy.',
'A lengthy journey down an internet rabbit hole begins with a single click.',
'Today, for once, no one will bug you about fixing their computer.',
'Do or do not submit a Incident, there is no try.',
'This is one cookie that can’t be deleted.',
'What your users don’t know about IT … keeps you employed. Relax.',
'A system reboot is in your future. Of this I am certain.',
'Your IT talents will not go unnoticed … by friends in need of tech support.',
'System Error: Fortune not found. Please contact your system administrator.',
'Copilot says: It looks like you’re eating a cookie. Would you like help?',
'If you build it, users will find a way to break it.',
'Error: This fortune requires cookies to be enabled before you proceed.',
'Many facepalms experienced ultimately make you a stronger person.',
'Not testing your backups is like asking for disaster.',
'Life in IT isn’t always a PICNIC. It can also be a PEBCAK.',
'True happiness in IT is an empty ticket queue.',
'I’d tell you a joke about cookies and data, but it kind of bytes.',
]
